#SingleInstance FORCE
 
;This is a script that is an internal timer. It tells you to flick Rapid Heal at NMZ every 49 seconds to keep at 1 hp.
;Also tells you to repot every 5 minutes. This timer has a sound and visual cue.
;GhostCalib3r is the best Kappa
 
 
loop,
 
{
 
 
 
loop, 5
 
{
MsgBox, 64, FLICKING TIME!, Flick Rapid Heal! Make sure it's not Rapid Restore. , .2
MsgBox, 64, FLICKING TIME!, Flick Rapid Heal! Make sure it's not Rapid Restore. , .2
MsgBox, 64, FLICKING TIME!, Flick Rapid Heal! Make sure it's not Rapid Restore. , .2
MsgBox, 64, FLICKING TIME!, Flick Rapid Heal! Make sure it's not Rapid Restore. , .2
 
 
 
MsgBox, 64, FLICKING TIME!, Flick Rapid Heal! Make sure it's not Rapid Restore. New message in 49 seconds. , 3
 
 
Sleep, 44000
 
 
 
 
}
 
 
 
 
 
 
 
MsgBox, 16, Test, REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT and Flick Rapid Heal! Make sure it's not Rapid Restore. , .2
 
MsgBox, 16, Test, REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT and Flick Rapid Heal! Make sure it's not Rapid Restore. , .2
 
MsgBox, 16, Test, REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT and Flick Rapid Heal! Make sure it's not Rapid Restore. , .2
 
MsgBox, 16, Test, REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT and Flick Rapid Heal! Make sure it's not Rapid Restore. , .2
 
 
 
 
 
 
MsgBox, 16, Test, REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT REPOT and Flick Rapid Heal! Make sure it's not Rapid Restore. New message in 49 seconds. , 3
 
 
 
Sleep, 44000
 
 
 
 
}
 
 
 
;ESC::ExitApp